export interface Product {
  id: string;
  title: string;
  image: string;
  description: string;
  category: "electronics" | "fashion" | "fitness" | "gifts" | "lifestyle";
  price: number;
  rating: number;
  stock: number;
  trendScore: number;
  growth: number;
  popularity: "Low" | "Medium" | "High" | "Exponential" | "Viral";
  features: string[];
  pros: string[];
  cons: string[];
  valueScore: number;
  banditWeight: number;
}

export const INITIAL_PRODUCTS: Product[] = [
  // ELECTRONICS (1-5)
  {
    id: "elec-1",
    title: "Quantum Buds Pro",
    image: "https://images.unsplash.com/photo-1590658268037-6bf12165a8df?auto=format&fit=crop&w=500&q=80",
    description: "Hybrid ANC earbuds featuring high-fidelity graphene drivers, spatial sound tracking, and a 40-hour premium battery casing.",
    category: "electronics",
    price: 189,
    rating: 4.8,
    stock: 45,
    trendScore: 94,
    growth: 14.5,
    popularity: "High",
    features: ["Active Noise Cancelling", "40-Hour Battery", "Spatial Audio", "IPX7 Sweatproof"],
    pros: ["Superb noise cancellation", "Extremely comfortable", "Stellar spatial stage"],
    cons: ["Slightly bulky case", "Premium pricing"],
    valueScore: 92,
    banditWeight: 1.0,
  },
  {
    id: "elec-2",
    title: "Zenith Stand Hub",
    image: "https://images.unsplash.com/photo-1622445262465-2481c4574875?auto=format&fit=crop&w=500&q=80",
    description: "All-in-one aerospace-grade aluminum inductive stand charging up to 3 devices simultaneously at ultra-fast speeds.",
    category: "electronics",
    price: 79,
    rating: 4.6,
    stock: 120,
    trendScore: 88,
    growth: 8.2,
    popularity: "Medium",
    features: ["Aviation Aluminum", "15W Fast Charge", "MagSafe Approved", "Overheat Cutoff"],
    pros: ["Elegant workspace design", "Very strong magnets", "Single cord setup"],
    cons: ["Doesn't include brick", "Static viewing angle"],
    valueScore: 85,
    banditWeight: 1.0,
  },
  {
    id: "elec-3",
    title: "AeroTrack Cinematic Drone",
    image: "https://images.unsplash.com/photo-1508614589041-895b88991e3e?auto=format&fit=crop&w=500&q=80",
    description: "Modular folding drone equipped with a mechanical 3-axis 4K gimbal, omnidirectional LiDAR obstacle escape tech.",
    category: "electronics",
    price: 699,
    rating: 4.9,
    stock: 15,
    trendScore: 98,
    growth: 32.4,
    popularity: "Exponential",
    features: ["4K HDR 60FPS", "LiDAR Collision Avoidance", "35-Min Flight Time", "Wind Resistance Level 6"],
    pros: ["Perfect tracking precision", "Ultra smooth gimbal", "Compact folding frames"],
    cons: ["High initial learning curve", "Requires registration in some sectors"],
    valueScore: 96,
    banditWeight: 1.0,
  },
  {
    id: "elec-4",
    title: "Chronos Band Active",
    image: "https://images.unsplash.com/photo-1575311373937-040b8e1fd5b6?auto=format&fit=crop&w=500&q=80",
    description: "Ultra-thin continuous wearable analyzing ambient HRV, skin temperature fluctuation, and blood oxygen levels in real-time.",
    category: "electronics",
    price: 149,
    rating: 4.5,
    stock: 67,
    trendScore: 85,
    growth: 5.5,
    popularity: "Medium",
    features: ["Haptic Pulse Monitor", "Sleep Quality Index", "Waterproof 50m", "5-Day Battery Life"],
    pros: ["Featherlight zero-screen wear", "In-depth heart analysis", "Elegant custom bands"],
    cons: ["App subscription unlocks full features", "Charging connector is proprietary"],
    valueScore: 81,
    banditWeight: 1.0,
  },
  {
    id: "elec-5",
    title: "Apex Mechanical Deck",
    image: "https://images.unsplash.com/photo-1587829741301-dc798b83add3?auto=format&fit=crop&w=500&q=80",
    description: "A compact 75% mechanical layout deck with hot-swappable linear yellow switches, double-shot PBT keycaps and frosted body.",
    category: "electronics",
    price: 129,
    rating: 4.7,
    stock: 35,
    trendScore: 92,
    growth: 12.1,
    popularity: "High",
    features: ["Hot-Swappable Sockets", "Triple Mode Connection", "Polycarbonate Plate", "Custom Gasket Mounted"],
    pros: ["Incredibly satisfying acoustics", "Zero-latency latency profiles", "Stunning ambient diffusion"],
    cons: ["Heavy travel weight", "No dedicated number pad"],
    valueScore: 89,
    banditWeight: 1.0,
  },

  // FASHION (6-10)
  {
    id: "fash-1",
    title: "Urban Nomad Tech Parka",
    image: "https://images.unsplash.com/photo-1544022613-e87ca75a784a?auto=format&fit=crop&w=500&q=80",
    description: "Three-in-one modular outerwear featuring high-density stormproofing, micro-fleece insulating layer, and 8 hidden gear slots.",
    category: "fashion",
    price: 245,
    rating: 4.8,
    stock: 22,
    trendScore: 95,
    growth: 19.8,
    popularity: "High",
    features: ["GoreTex Weave", "Magnetic Closures", "Packable Hood", "Sub-Zero Rated Protection"],
    pros: ["Complete storm windproofing", "Adapts to 3 seasons easily", "Clever concealed pockets"],
    cons: ["Dry clean only recommended", "Slightly rigid high collar"],
    valueScore: 93,
    banditWeight: 1.0,
  },
  {
    id: "fash-2",
    title: "VaporGrid High-Tops",
    image: "https://images.unsplash.com/photo-1542291026-7eec264c27ff?auto=format&fit=crop&w=500&q=80",
    description: "Eco-conscious knit performance sneakers constructed from marine plastics with dynamic carbon fiber energy rebound plates.",
    category: "fashion",
    price: 160,
    rating: 4.6,
    stock: 40,
    trendScore: 91,
    growth: 10.4,
    popularity: "High",
    features: ["Recycled Ocean Weave", "Carbon Plate Midsole", "Adaptive Heel Grip", "Ortholite Antimicrobial Sockliner"],
    pros: ["Very bouncy step momentum", "Breathable like standard knit", "Incredible eco footprint"],
    cons: ["Prone to wet weather soak", "Fits narrow in standard toebox"],
    valueScore: 87,
    banditWeight: 1.0,
  },
  {
    id: "fash-3",
    title: "Merino Breeze Nomad Tee",
    image: "https://images.unsplash.com/photo-1521572267360-ee0c2909d518?auto=format&fit=crop&w=500&q=80",
    description: "Odor-resistant 100% fine New Zealand merino wool shirt designed for optimal thermal regulation across temperature swings.",
    category: "fashion",
    price: 65,
    rating: 4.4,
    stock: 90,
    trendScore: 82,
    growth: 3.2,
    popularity: "Medium",
    features: ["18.5 Micron Merino Wool", "Naturally Anti-Odor", "Moisture Wicking Weave", "Reinforced Flatlock Seams"],
    pros: ["Smell-free after multiple wears", "Silky soft skin profile", "Excellent thermal balancing"],
    cons: ["Requires flat drying", "More prone to micro-tears than blends"],
    valueScore: 83,
    banditWeight: 1.0,
  },
  {
    id: "fash-4",
    title: "Luna Carbon Slim Wallet",
    image: "https://images.unsplash.com/photo-1627123424574-724758594e93?auto=format&fit=crop&w=500&q=80",
    description: "Sleek card-carrier block milled from continuous 3K carbon-fiber sheet. Holds 12 cards with spring tension cash clip.",
    category: "fashion",
    price: 45,
    rating: 4.7,
    stock: 150,
    trendScore: 89,
    growth: 7.8,
    popularity: "High",
    features: ["3K Dry Carbon Fiber", "RFID Blocking Array", "Integrated Cash Clip", "Instant Beveled Thumb Slide"],
    pros: ["Incredibly thin front-pocket fit", "Indestructible carbon shield", "Easy cash access"],
    cons: ["No coin hold option", "Slightly stiff initially"],
    valueScore: 90,
    banditWeight: 1.0,
  },
  {
    id: "fash-5",
    title: "Titan Solas Aviators",
    image: "https://images.unsplash.com/photo-1511499767150-a48a237f0083?auto=format&fit=crop&w=500&q=80",
    description: "Featherweight beta-titanium wireframe sunglasses with category-3 polarized sapphire lenses with anti-reflective coating.",
    category: "fashion",
    price: 195,
    rating: 4.8,
    stock: 18,
    trendScore: 93,
    growth: 11.2,
    popularity: "High",
    features: ["Beta-Titanium Framing", "Sapphire Shield Coating", "100% UV Ray Block", "Anti-Slip Silicone Nose Pads"],
    pros: ["Virtually unnoticeable on ears", "Zero lens distortion", "Classic architectural styling"],
    cons: ["Highly delicate frame design", "Premium price tier"],
    valueScore: 86,
    banditWeight: 1.0,
  },

  // FITNESS (11-15)
  {
    id: "fit-1",
    title: "FlexGrip Selector Dumbbell",
    image: "https://images.unsplash.com/photo-1638536532686-d610adfc8e5c?auto=format&fit=crop&w=500&q=80",
    description: "Compact dual dumbbells replacing 10 pairs with rapid click dials, adjusting weight instantly from 5 to 52.5 lbs.",
    category: "fitness",
    price: 329,
    rating: 4.8,
    stock: 14,
    trendScore: 96,
    growth: 28.5,
    popularity: "Exponential",
    features: ["Quick-Click Adjustment Dial", "Textured Steel Ergonomic Handle", "Dense ABS Clad Steel Plates", "Safe Locking Mechanism"],
    pros: ["Massive workspace space-saver", "Durable indexing dial", "Excellent heavy knurling"],
    cons: ["Slightly wider than single weights", "Cannot be dropped heavily"],
    valueScore: 94,
    banditWeight: 1.0,
  },
  {
    id: "fit-2",
    title: "AeroCore Studio Mat",
    image: "https://images.unsplash.com/photo-1592432678016-e910b452f9a2?auto=format&fit=crop&w=500&q=80",
    description: "High-density polyurethane yoga mat offering unparalleled wet and dry grip with lasered guiding alignment vectors.",
    category: "fitness",
    price: 85,
    rating: 4.7,
    stock: 55,
    trendScore: 89,
    growth: 6.7,
    popularity: "Medium",
    features: ["Eco Polyurethane Top", "Natural Rubber Base Mesh", "Laser alignment guides", "6mm Dense Ortho Cushioning"],
    pros: ["Completely slip-proof in sweat", "Extremely dense floor safety", "Odour shield surface"],
    cons: ["Rubber smell first 2 days", "Relatively heavy weight to roll"],
    valueScore: 88,
    banditWeight: 1.0,
  },
  {
    id: "fit-3",
    title: "HydroFlow Smart Flask",
    image: "https://images.unsplash.com/photo-1602143407151-7111542de6e8?auto=format&fit=crop&w=500&q=80",
    description: "Double-walled steel vessel with a UV-C LED sterilizing cap neutralizing 99.9% of biological contaminants automatically.",
    category: "fitness",
    price: 95,
    rating: 4.6,
    stock: 80,
    trendScore: 91,
    growth: 13.2,
    popularity: "High",
    features: ["Intelligent UV-C Cover", "Vacuum Sealed 24-Hr Cold", "Real-time Temperature Check", "Stoneware Matte Outer Coating"],
    pros: ["Odorless, clean water always", "Long battery life on charging", "Excellent temperature lock"],
    cons: ["Charging cord is unconventional", "Cap is hand-wash only"],
    valueScore: 86,
    banditWeight: 1.0,
  },
  {
    id: "fit-4",
    title: "VeloCycle Connected Frame",
    image: "https://images.unsplash.com/photo-1517838277536-f5f99be501cd?auto=format&fit=crop&w=500&q=80",
    description: "Premium silent magnetic indoor studio bike with integrated 22-inch high fidelity display for coach-guided regimens.",
    category: "fitness",
    price: 1499,
    rating: 4.9,
    stock: 8,
    trendScore: 97,
    growth: 24.1,
    popularity: "Exponential",
    features: ["Quiet-Drive Belt Resistance", "22-Inch Rotational Touch Panel", "Precision Power Metric Track", "Adjustable Seat/Bars Assembly"],
    pros: ["Whisper-silent resistance system", "Stunning cinematic workout feeds", "Industrial build quality"],
    cons: ["High up-front equipment investment", "Requires digital program member plan"],
    valueScore: 91,
    banditWeight: 1.0,
  },
  {
    id: "fit-5",
    title: "PulseGuard ECG Tracker",
    image: "https://images.unsplash.com/photo-1507398941214-572c25f4b1dc?auto=format&fit=crop&w=500&q=80",
    description: "Professional chest strap transmitting real-time physical-grade ECG graphs over double-channel Bluetooth/ANT+.",
    category: "fitness",
    price: 89,
    rating: 4.5,
    stock: 95,
    trendScore: 84,
    growth: 4.1,
    popularity: "Medium",
    features: ["Dual Band BT & ANT+", "Medical Grade ECG Sampling", "Machine washable high elasticity strap", "Over 400 Hours Battery Life"],
    pros: ["Extremely accurate tracking", "Instant pairing with fitness gear", "Long battery life"],
    cons: ["Slightly constricting layout", "No on-device display tracking"],
    valueScore: 84,
    banditWeight: 1.0,
  },

  // GIFTS (16-20)
  {
    id: "gift-1",
    title: "Nebula Glass Diffuser",
    image: "https://images.unsplash.com/photo-1519681393784-d120267933ba?auto=format&fit=crop&w=500&q=80",
    description: "Waterless cold-nebulizing pure oil diffuser cased in mouth-blown lead-free gradient borosilicate glassware.",
    category: "gifts",
    price: 110,
    rating: 4.7,
    stock: 42,
    trendScore: 92,
    growth: 15.6,
    popularity: "High",
    features: ["Pure Waterless Nebulizer", "Borosilicate Artisan Frame", "Integrated Pulsing Warm LEDs", "Silent Pump Engine"],
    pros: ["Does not raise room humidity", "Elegant design lighting focus", "Fills large rooms extremely fast"],
    cons: ["Consumes pure oils slightly faster", "Glass requires delicate dusting"],
    valueScore: 89,
    banditWeight: 1.0,
  },
  {
    id: "gift-2",
    title: "Precision Scribe Executive",
    image: "https://images.unsplash.com/photo-1583485088034-697b5bc54ccd?auto=format&fit=crop&w=500&q=80",
    description: "Sleek machined brass executive pen designed for ultimate weight balancing, fitted with German iridium nib.",
    category: "gifts",
    price: 95,
    rating: 4.6,
    stock: 60,
    trendScore: 86,
    growth: 6.2,
    popularity: "Medium",
    features: ["C360 Machined Solid Brass", "German Fine Iridium Nib", "Rotary Ink Converter Array", "Screw-On Thread Locking Protection"],
    pros: ["Forms lovely natural patina", "Superbly balanced ink line", "Sophisticated presenting box"],
    cons: ["Heavier than standard resin pens", "Must be cleaned monthly"],
    valueScore: 86,
    banditWeight: 1.0,
  },
  {
    id: "gift-3",
    title: "Atlas Copper Scratch Globe",
    image: "https://images.unsplash.com/photo-1589301760014-d929f3979dbc?auto=format&fit=crop&w=500&q=80",
    description: "Stunning geographical focal map lined in rich copper foil that scratches cleanly to reveal vivid travel colors.",
    category: "gifts",
    price: 55,
    rating: 4.8,
    stock: 75,
    trendScore: 87,
    growth: 8.9,
    popularity: "High",
    features: ["Copper Mirror Foil Map", "Aviation Double Gimbal Stand", "Precision Scratch Tool", "Enclosed Travel Diary Booklet"],
    pros: ["Stunning office conversationalist", "Scratch barrier doesn't flake off", "Highly detailed cartography"],
    cons: ["Foil can scratch by accident if mishandled", "Takes up decent desk footprint"],
    valueScore: 92,
    banditWeight: 1.0,
  },
  {
    id: "gift-4",
    title: "Ember Temp Control Mug",
    image: "https://images.unsplash.com/photo-1514432324607-a09d9b4aefdd?auto=format&fit=crop&w=500&q=80",
    description: "Smart ceramic mug paired with interactive heating base that maintains your coffee or tea at the exact degree desired.",
    category: "gifts",
    price: 135,
    rating: 4.5,
    stock: 30,
    trendScore: 93,
    growth: 18.2,
    popularity: "High",
    features: ["Inductive Coaster Base", "Precision Custom Temp App", "Smart Sleep Auto-Trigger", "Double Coated Ceramic Finish"],
    pros: ["Coffee never cools down", "Elegantly finished hand grip", "Waterproof and fully submersible"],
    cons: ["Battery lasts 1.5 hours off plate", "Not microwave or dishwasher safe"],
    valueScore: 82,
    banditWeight: 1.0,
  },
  {
    id: "gift-5",
    title: "Stellar Galaxy Orb",
    image: "https://images.unsplash.com/photo-1543002588-bfa74002ed7e?auto=format&fit=crop&w=500&q=80",
    description: "Hand-blown solid glass orb storing a highly detailed 3D laser-etched milky way map on a dark walnut light mount.",
    category: "gifts",
    price: 49,
    rating: 4.9,
    stock: 110,
    trendScore: 95,
    growth: 21.3,
    popularity: "Viral",
    features: ["K9 Optical Glass Orb", "Walnut Dynamic Glow Stand", "Precision Lasered Structure", "USB Touch Adjustment Interface"],
    pros: ["Sublime ambient decoration", "True scale relative map", "Pleasant amber emission"],
    cons: ["Slightly heavy core orb", "Cord feels generic white plastic"],
    valueScore: 95,
    banditWeight: 1.0,
  },

  // LIFESTYLE (21-25)
  {
    id: "life-1",
    title: "Terra Stoneware Press",
    image: "https://images.unsplash.com/photo-1544787219-7f47ccb76574?auto=format&fit=crop&w=500&q=80",
    description: "Stoneware press utilizing double-wall insulation with brushed copper plunger and fine micro-mesh filter basket.",
    category: "lifestyle",
    price: 85,
    rating: 4.7,
    stock: 48,
    trendScore: 90,
    growth: 11.4,
    popularity: "Medium",
    features: ["Double-Wall Stoneware Plate", "Medical Copper Gilded Cap", "Double Mesh Filter Weave", "Soft Pour Silicone Lip"],
    pros: ["Keeps coffee hot for hours", "Beautiful matte aesthetic", "Zero grounds pass filter"],
    cons: ["Heavier than glass presses", "Requires manual hand brushing"],
    valueScore: 90,
    banditWeight: 1.0,
  },
  {
    id: "life-2",
    title: "AeroPurify Active Tower",
    image: "https://images.unsplash.com/photo-1585338111522-a3n1b2c34a1a?auto=format&fit=crop&w=500&q=80",
    description: "Tower active air scrubber utilizing true HEPA H13 layers, activated coconut shell charcoal, and dynamic laser sensor indices.",
    category: "lifestyle",
    price: 199,
    rating: 4.8,
    stock: 20,
    trendScore: 94,
    growth: 22.1,
    popularity: "Exponential",
    features: ["H13 Medical HEPA Grid", "Coconut Active Carbon Filter", "Smart Automatic Fan Driver", "Ambient Air Metric Lamp"],
    pros: ["Incredibly quiet whisper mode", "Vastly improves sleep air", "Accurate particle metric monitoring"],
    cons: ["Filter sets are recurring expense", "Decent physical room space occupied"],
    valueScore: 91,
    banditWeight: 1.0,
  },
  {
    id: "life-3",
    title: "Belgian Flax Linen Set",
    image: "https://images.unsplash.com/photo-1505693416388-ac5ce068fe85?auto=format&fit=crop&w=500&q=80",
    description: "Premium organic linen sheets woven from fine Belgian flax fibers, pre-washed with volcanic pumice for buttery touch.",
    category: "lifestyle",
    price: 220,
    rating: 4.8,
    stock: 32,
    trendScore: 93,
    growth: 14.8,
    popularity: "High",
    features: ["100% Belgian Organic Flax", "Stone Pre-washed Fiber Finish", "Deep Pocket Fitted Elastic", "OEKO-TEX Green Certified"],
    pros: ["Incredibly breathable in summer", "Gets softer with every wash cycle", "Lustrous relaxed rumpled drape"],
    cons: ["Easily creases naturally", "Loses excess fluff during first laundering"],
    valueScore: 93,
    banditWeight: 1.0,
  },
  {
    id: "life-4",
    title: "Somnus Calm Weighted Blanket",
    image: "https://images.unsplash.com/photo-1580301762395-21ce84d00bc6?auto=format&fit=crop&w=500&q=80",
    description: "15-pound weighted blanket filled with medical-grade micro-glass beads sewn into breathable grid-channel bamboo sheets.",
    category: "lifestyle",
    price: 125,
    rating: 4.6,
    stock: 38,
    trendScore: 89,
    growth: 8.5,
    popularity: "Medium",
    features: ["Silky Smooth Lyocell Bamboo", "Non-Toxic Micro Glass Beads", "Small 10x10cm Shifting-Free Pockets", "Sturdy Loop Quilt Connector Ties"],
    pros: ["Soothes nervous system immediately", "Perfect temperature neutralization", "Machine-washable zip cover"],
    cons: ["Heavy for shifting sheets", "Bamboo outer shell is slightly slippery"],
    valueScore: 87,
    banditWeight: 1.0,
  },
  {
    id: "life-5",
    title: "Komorebi Modular Desk Tray",
    image: "https://images.unsplash.com/photo-1513151233558-d860c5398176?auto=format&fit=crop&w=500&q=80",
    description: "Modular magnetic desk organizer milled from rich solid FSC-certified black walnut and anodized sandblasted aluminum.",
    category: "lifestyle",
    price: 79,
    rating: 4.7,
    stock: 72,
    trendScore: 91,
    growth: 11.5,
    popularity: "High",
    features: ["FSC Certified Black Walnut", "Inductive Magnetic Snap Rails", "Sandblasted Aluminum Compartments", "Soft Cork Padding Base Protection"],
    pros: ["Beautiful structural desk lines", "Easily rearrange components", "Hidden magnetic pen tracks"],
    cons: ["Does not fit bulky tech blocks well", "Walnut requires seasonal light oiling"],
    valueScore: 88,
    banditWeight: 1.0,
  },
];

export interface VisualSearchPreset {
  id: string;
  name: string;
  imageUrl: string;
  detectedCategory: string;
  confidence: number;
  explanation: string;
  similarProductIds: string[];
}

export const VISUAL_SEARCH_PRESETS: VisualSearchPreset[] = [
  {
    id: "vs-1",
    name: "Acoustic Earbuds Image",
    imageUrl: "https://images.unsplash.com/photo-1590658268037-6bf12165a8df?auto=format&fit=crop&w=150&q=80",
    detectedCategory: "electronics",
    confidence: 96.8,
    explanation: "AI detected a modern set of in-ear acoustic headphones with active charging pins and silicon adapters. Perfectly matches the Electronics/Audio classification.",
    similarProductIds: ["elec-1", "elec-4", "elec-2"],
  },
  {
    id: "vs-2",
    name: "Outdoor Raincoat Image",
    imageUrl: "https://images.unsplash.com/photo-1544022613-e87ca75a784a?auto=format&fit=crop&w=150&q=80",
    detectedCategory: "fashion",
    confidence: 94.2,
    explanation: "AI identified structural synthetic microfiber layers, heavy-duty weather hood contouring, and magnetic draft closures. Perfect match for Technical Wear / Outerwear.",
    similarProductIds: ["fash-1", "fash-3", "fash-5"],
  },
  {
    id: "vs-3",
    name: "Steel Insulated Flask Image",
    imageUrl: "https://images.unsplash.com/photo-1602143407151-7111542de6e8?auto=format&fit=crop&w=150&q=80",
    detectedCategory: "fitness",
    confidence: 91.5,
    explanation: "AI localized a double-walled powder-coated cylindrical thermal vessel with continuous micro-sealed cap threadings. Corresponds to active performance gear.",
    similarProductIds: ["fit-3", "fit-2", "fit-5"],
  },
  {
    id: "vs-4",
    name: "Exec Desk Pen Image",
    imageUrl: "https://images.unsplash.com/photo-1583485088034-697b5bc54ccd?auto=format&fit=crop&w=150&q=80",
    detectedCategory: "gifts",
    confidence: 98.1,
    explanation: "AI scanned a precision balanced lathe-cut metal alloy writing instrument with executive iridium feed tip. Strongly indicates stationery gifts class.",
    similarProductIds: ["gift-2", "gift-1", "gift-4"],
  },
];
